### ISSUE TITLE
How can I find the paper

### ISSUE THREAD

**Issue by LLMforScience** [AISafety-HKUST/stable_backdoor_purification#1]
Thank you for your work. I am very interested in your work. Can I know where I can find the pre-print of the paper?

**Comment by AISafety-HKUST** [comment]
> Thank you for your work. I am very interested in your work. Can I know where I can find the pre-print of the paper?

Hi, thanks for your appreciation. We are still organizing the source code and pre-print paper and plan to release them in this week!

**Comment by Alan-Qin** [comment]
Thanks for your attention. Our arxiv version: https://arxiv.org/abs/2310.01875

**Comment by LLMforScience** [comment]
Thank you!
